"""initial

Revision ID: c834f2e28e37
Revises: 
Create Date: 2025-12-06 02:17:20.699257

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c834f2e28e37'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jobs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_address', sa.String(), nullable=False),
    sa.Column('c3_job_id', sa.String(), nullable=False),
    sa.Column('gpu_type', sa.String(), nullable=False),
    sa.Column('image', sa.String(), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=False),
    sa.Column('cost_usd', sa.Float(), nullable=False),
    sa.Column('cost_bnb', sa.Float(), nullable=False),
    sa.Column('bnb_price_usd', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jobs_user_address'), 'jobs', ['user_address'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_jobs_user_address'), table_name='jobs')
    op.drop_table('jobs')
    # ### end Alembic commands ###
